FROM golang:1.16-alpine AS build

RUN apk add --no-cache git
RUN go get github.com/golang/dep/cmd/dep
#dependencies install from src dest
COPY Gopkg.lock Gopkg.toml /home/go/
WORKDIR /home/go/
# Install library dependencies
RUN dep ensure -vendor-only

COPY . /home/go/
RUN go build -o /bin/main

# This results in a single layer image
FROM alpine
COPY --from=build /bin/main /bin/main
ENTRYPOINT ["/bin/main"]
CMD ["--help"]