version: '3'
services:
  mysql:
    image: mysql:8.0.33
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqladmin
      - MYSQL_USER=nodeapi
      - MYSQL_PASSWORD=uadareu1234437
      - MYSQL_DATABASE=api_db
    ports:
      - 3306:3306
    networks:
      - api
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pmysqladmin"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./api/app:/home/node/app
    environment:
      - ENV=prod
      - DATABASE_URL=mysql://root:mysqladmin@mysql:3306/api_db
    ports:
      - 3000:3000
    networks:
      - api
    entrypoint:
       - npm
       - run
       - start-dev
networks:
  api:
    driver: bridge  
