apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
      - name: install
        image: node:18.12.1-alpine3
        command: ['sh', '-c', "cd /home/node && git clone $REPO_CLONE"]
        env:
          - name: REPO_CLONE
            value: https://github.com/iagoambrosio/demo-microservice
      volumeMounts:
      - name: workdir
        mountPath: "/home/node"
      containers:
      - name: node
        image: node:18.12.1-alpine3
        command:  ['sh', '-c', "cd /home/node/demo-microservice/api && npm install && npm start"]
        port: 3000
        volumeMounts:
        - name: workdir
          mountPath: "/home/node"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
