apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  serviceName: "mysql-database"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.33
        name: mysqld
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysqladmin"
        - name: MYSQL_USER
          value: "nodeapi"
        - name: MYSQL_PASSWORD
          value: "uadareu1234437"
        - name: MYSQL_DATABASE
          value: "api_db"
