name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Sign the published Docker image
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: docker login -u $(secrets.DOCKERHUB_USER) -p $(secrets.DOCKERHUB_TOKEN)
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: iago0silva/api:1.0
          context: .
          file: Dockerfile.api
